module.exports = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary-fixed": "#001d33",
        "on-secondary-fixed": "#001f28",
        "on-secondary-container": "#00566a",
        "tertiary-fixed-dim": "#4edea3",
        "on-secondary-fixed-variant": "#004e60",
        "inverse-on-surface": "#2b3139",
        error: "#ffb4ab",
        "outline-variant": "#3f4852",
        "on-error-container": "#ffdad6",
        "tertiary-fixed": "#6ffbbe",
        outline: "#88919d",
        "surface-container-high": "#252a32",
        "on-primary-fixed-variant": "#004a77",
        "primary-fixed-dim": "#98cbff",
        "on-surface": "#dde3ed",
        secondary: "#a5e7ff",
        "surface-dim": "#0e141b",
        "surface-container-highest": "#2f353d",
        "on-surface-variant": "#bec7d4",
        "on-tertiary-fixed": "#002113",
        primary: "#98cbff",
        "secondary-fixed-dim": "#47d6ff",
        "on-background": "#dde3ed",
        "secondary-fixed": "#b6ebff",
        tertiary: "#4edea3",
        "surface-container": "#1a2027",
        "on-error": "#690005",
        "on-tertiary-container": "#003c27",
        "on-tertiary-fixed-variant": "#005236",
        "surface-variant": "#2f353d",
        "surface-tint": "#98cbff",
        "secondary-container": "#00d2ff",
        "on-primary-container": "#00375a",
        "on-secondary": "#003543",
        "surface-container-low": "#161c23",
        "tertiary-container": "#00b27b",
        "surface-bright": "#343a42",
        "primary-container": "#00a3ff",
        "inverse-primary": "#00629d",
        "primary-fixed": "#cfe5ff",
        background: "#0e141b",
        "error-container": "#93000a",
        "surface-container-lowest": "#090f16",
        "on-tertiary": "#003824",
        "on-primary": "#003354",
        surface: "#0e141b",
        "inverse-surface": "#dde3ed",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "space-xs": "0.25rem",
        "space-xl": "2rem",
        "space-2xl": "3rem",
        "gutter-mobile": "0.75rem",
        margin: "2rem",
        "margin-mobile": "1rem",
        "space-sm": "0.5rem",
        "space-lg": "1.5rem",
        "space-md": "1rem",
        gutter: "1.25rem",
      },
      fontFamily: {
        "body-sm": ["Inter", "ui-sans-serif", "system-ui", "sans-serif"],
        "display-mobile": ["Inter", "ui-sans-serif", "system-ui", "sans-serif"],
        "body-lg": ["Inter", "ui-sans-serif", "system-ui", "sans-serif"],
        "title-md": ["Inter", "ui-sans-serif", "system-ui", "sans-serif"],
        "headline-md": ["Inter", "ui-sans-serif", "system-ui", "sans-serif"],
        "headline-lg-mobile": [
          "Inter",
          "ui-sans-serif",
          "system-ui",
          "sans-serif",
        ],
        "label-md": ["Inter", "ui-sans-serif", "system-ui", "sans-serif"],
        display: ["Inter", "ui-sans-serif", "system-ui", "sans-serif"],
        "body-md": ["Inter", "ui-sans-serif", "system-ui", "sans-serif"],
        "label-sm": ["Inter", "ui-sans-serif", "system-ui", "sans-serif"],
        "title-sm": ["Inter", "ui-sans-serif", "system-ui", "sans-serif"],
        "headline-lg": ["Inter", "ui-sans-serif", "system-ui", "sans-serif"],
        "headline-sm": ["Inter", "ui-sans-serif", "system-ui", "sans-serif"],
        "code-sm": ["Inter", "ui-sans-serif", "system-ui", "sans-serif"],
      },
      fontSize: {
        "body-sm": [
          "0.8125rem",
          {
            lineHeight: "1.25rem",
            letterSpacing: "0.01em",
            fontWeight: "400",
          },
        ],
        "display-mobile": [
          "2.25rem",
          {
            lineHeight: "2.75rem",
            letterSpacing: "-0.02em",
            fontWeight: "700",
          },
        ],
        "body-lg": [
          "1.125rem",
          {
            lineHeight: "1.75rem",
            letterSpacing: "0em",
            fontWeight: "400",
          },
        ],
        "title-md": [
          "1.125rem",
          {
            lineHeight: "1.625rem",
            letterSpacing: "-0.005em",
            fontWeight: "600",
          },
        ],
        "headline-md": [
          "1.5rem",
          {
            lineHeight: "2rem",
            letterSpacing: "-0.015em",
            fontWeight: "600",
          },
        ],
        "headline-lg-mobile": [
          "1.5rem",
          {
            lineHeight: "2rem",
            letterSpacing: "-0.015em",
            fontWeight: "600",
          },
        ],
        "label-md": [
          "0.875rem",
          {
            lineHeight: "1.25rem",
            letterSpacing: "0.01em",
            fontWeight: "500",
          },
        ],
        display: [
          "3rem",
          {
            lineHeight: "3.5rem",
            letterSpacing: "-0.025em",
            fontWeight: "700",
          },
        ],
        "body-md": [
          "0.9375rem",
          {
            lineHeight: "1.5rem",
            letterSpacing: "0em",
            fontWeight: "400",
          },
        ],
        "label-sm": [
          "0.75rem",
          {
            lineHeight: "1rem",
            letterSpacing: "0.04em",
            fontWeight: "600",
          },
        ],
        "title-sm": [
          "1rem",
          {
            lineHeight: "1.5rem",
            letterSpacing: "0em",
            fontWeight: "600",
          },
        ],
        "headline-lg": [
          "2rem",
          {
            lineHeight: "2.5rem",
            letterSpacing: "-0.02em",
            fontWeight: "700",
          },
        ],
        "headline-sm": [
          "1.25rem",
          {
            lineHeight: "1.75rem",
            letterSpacing: "-0.01em",
            fontWeight: "600",
          },
        ],
        "code-sm": [
          "0.75rem",
          {
            lineHeight: "1rem",
            letterSpacing: "0.02em",
            fontWeight: "500",
          },
        ],
      },
    },
  },
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  corePlugins: {
    preflight: false,
  },
};
