import React from "react";
import {
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowUpRight,
  ArrowLeftRight,
  BookmarkCheck,
  Zap,
  CircleCheck,
  Calendar,
  Lock,
  Brain,
  Radar,
  Clock,
  Send,
  Share2,
  RefreshCw,
  ThumbsDown,
  ThumbsUp,
  TrendingUp,
  BadgeCheck,
  Video,
  Eye,
  FileText,
  Sparkles,
  Copy,
  Database,
  Compass,
  CircleHelp,
  History,
  Network,
  ChartNoAxesCombined,
  BellOff,
  Images,
  CirclePlay,
  Search,
  Star,
  PanelsTopLeft,
  Plus,
  WandSparkles,
  Check,
  X,
  ChevronDown,
  Users,
  Lightbulb,
  Film,
  Play,
  Globe,
  Save,
  Hash,
  Timer,
  ChevronsUpDown,
  AlarmClock,
  ChevronRight,
  Pencil,
  MessageSquare,
  Image,
  SlidersHorizontal,
  ShieldCheck,
  Navigation,
  ScatterChart,
  Info,
  List,
  Radio,
  Car,
  Cpu,
  Palette,
  Rocket,
  Bot,
  Gamepad2,
  Terminal,
  LayoutPanelLeft,
} from "lucide-react";

const icons = {
  arrow_back: ArrowLeft,
  arrow_forward: ArrowRight,
  arrow_upward: ArrowUp,
  north_east: ArrowUpRight,
  compare_arrows: ArrowLeftRight,
  bookmark_added: BookmarkCheck,
  bolt: Zap,
  check_circle: CircleCheck,
  event: Calendar,
  event_available: Calendar,
  event_upcoming: Calendar,
  lock: Lock,
  psychology: Brain,
  radar: Radar,
  schedule: Clock,
  send: Send,
  share: Share2,
  sync: RefreshCw,
  refresh: RefreshCw,
  autorenew: RefreshCw,
  auto_mode: RefreshCw,
  thumb_down: ThumbsDown,
  thumb_up: ThumbsUp,
  trending_up: TrendingUp,
  verified: BadgeCheck,
  videocam: Video,
  visibility: Eye,
  article: FileText,
  notes: FileText,
  auto_awesome: Sparkles,
  copy_all: Copy,
  content_copy: Copy,
  database: Database,
  explore: Compass,
  help_outline: CircleHelp,
  history: History,
  hub: Network,
  insights: ChartNoAxesCombined,
  manage_search: Search,
  notifications_paused: BellOff,
  photo_library: Images,
  play_circle: CirclePlay,
  search: Search,
  star: Star,
  view_carousel: PanelsTopLeft,
  add: Plus,
  auto_fix_high: WandSparkles,
  check: Check,
  close: X,
  expand_more: ChevronDown,
  groups: Users,
  lightbulb: Lightbulb,
  movie: Film,
  play_arrow: Play,
  public: Globe,
  save: Save,
  tag: Hash,
  timer: Timer,
  unfold_more: ChevronsUpDown,
  alarm_on: AlarmClock,
  batch_prediction: Lightbulb,
  chevron_right: ChevronRight,
  edit_document: Pencil,
  forum: MessageSquare,
  image: Image,
  tune: SlidersHorizontal,
  verified_user: ShieldCheck,
  navigation: Navigation,
  scatter_plot: ScatterChart,
  info: Info,
  format_list_bulleted: List,
  sensors: Radio,
  directions_car: Car,
  format_image_left: LayoutPanelLeft,
  memory: Cpu,
  palette: Palette,
  rocket: Rocket,
  smart_toy: Bot,
  sports_esports: Gamepad2,
  terminal: Terminal,
};
export default function DesignIcon({ name, className = "" }) {
  const Icon = icons[name] || CircleHelp;
  return (
    <Icon
      aria-hidden="true"
      className={`design-icon ${name === "check" ? "check-icon" : ""} ${className}`}
    />
  );
}
